# This is a basic workflow to help you get started with Actions

name: Try GitHub

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World!"
